SAMZA-2544: Adding cleanup for Container Placement tests using threads, coordinator stream stores
**Improvement** [Bug fix]: Adding teardown / cleanup to Container placements integration tests

**API changes:** None

**Symptoms:**: Creates OOMs when test suite is executed
```
Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "RMI RenewClean-[]"
Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "Container Allocator Thread"
Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "RMI RenewClean-[]"
Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "ContainerPlacement Request Allocator Thread"
Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "Container Allocator Thread"
Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "Container Allocator Thread"
Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "Container Allocator Thread"
```

**Upgrade Instructions:** None

**Usage Instructions:** None

Author: Sanil15 <sanil.jain15@gmail.com>

Reviewers: mynameborat <bharathkk@apache.org>

Closes #1378 from Sanil15/oom-fix

(cherry picked from commit 8c753eb4ded7a7239f33042da903aa5fcc47dc75)
Signed-off-by: mynameborat <bharath.kumarasubramanian@gmail.com>